### ISSUE TITLE
[Anon] Bug report: HoRKT-Blood_Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-heralds-of-ruin-killteam#101]
**File:** HoRKT-Blood_Angels.catz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** No

**Description:** Not sure if this is a DataFile-Bug or BattleScribe-Bug: 
Tried to bulid a Blood Angels Killteam with Heralds of the Ruin Killteam-File. 
I added two Assault Marines, gave them a Jumppack and later added a third one an gave him also a Jumppack. With doing that the two old ones get an extra Jumppack (resulting in an error) and the checkbox changes to a counter. Found out that this only happens if you add a unit afterwards. Adding all three Assault Marines and then hitting the checkbox works fine. Could also be reproduced on Mac

**Comment by mathaius90** [comment]
Probably it's a datafile-related bug. Some constraint might have been linked to a global constant or something.
