### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by tectonicbg** [BSData/wh40k-heralds-of-ruin-killteam#108]
I'd like to see if I can help keep these files up to date.  Interested in starting work on Rogue Traders catalog.

**Comment by amis92** [comment]
Hello, @tectonicbg . Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also join our team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!
