### ISSUE TITLE
[Anon] Bug report: HoRKT-Tyranids.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-heralds-of-ruin-killteam#121]
**File:** HoRKT-Tyranids.catz

**BattleScribe version:** 2.16.73

**Platform:** Windows

**Dropbox:** No

**Description:** The Tyranid Ravener special operative is not fuctioning properly when it comes to it's ranged weapon option.  Per the rules PDF: "Wargear: A Ravener has three pairs of scything talons and a chitin carapace. It may also do any of the following:
Exchange one pair of scything talons for a pair of rending claws.
Take a pair of spinefists, a deathspitter or a devourer."

Currently the data file is requiring you to trade a pair of talons for the ravener's spinefists/deathspitter/devourer.  The ravener's gun is a chest-mounted weapon, it does not have to swap out a pair of talons.

**Comment by tdub415** [comment]
Please close this request, I accidently submitted to to heralds of ruin, it was supposed to be for shadow war Armageddon
