### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by GrissomKlyn** [BSData/wh40k-heralds-of-ruin-killteam#134]
Hi, I was hoping to help out with all of this, focusing on eventually bringing online Rogue Trade houses, Space Wolves and anything else that might be requested.

**Comment by GenWilhelm** [comment]
Hey there, very sorry I didn't get back to you before now.

If you're still interested in contributing, please let me know.

Again, massive apologies for the ridiculous delay.

**Comment by GenWilhelm** [comment]
Great!

I've invited you to be a collaborator on the repo, which you should have received an email about.
(Or you can find the invite here: https://github.com/BSData/wh40k-heralds-of-ruin-killteam/invitations)

If you need any help getting started, the people on the 40k repo's gitter are always happy to help (you'll find me in there, too!): https://gitter.im/BSData/wh40k

There's also the catalogue development repo, which has some useful resources: https://github.com/BSData/catalogue-development/blob/master/README.md
