### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by akodoyujo** [BSData/wh40k-heralds-of-ruin-killteam#3]
If I am understanding the ReadMe correctly, this is the place ask to join so I can gain access to the Kill Team data? Thank you!

**Comment by amis92** [comment]
Let me quote:
>**What's this?**
>
>BSData organisation created this project. It's GitHub repository of datafiles. Maintained by community, in no way endorsed by BattleScribe. If you want to develop - cool! We need you! Take a look at Getting Started wiki
>
>**Okay, nice project. Is it actually working? I just want those files...**
>
>Yeah! We have it hosted on AppSpot. Take a look: [BattleScribe Data on Appspot](http://battlescribedata.appspot.com/#/repos)

To have access to the datafiles, please follow link under second bulletpoint. :)
