### ISSUE TITLE
Space marines

### ISSUE THREAD

**Issue by dogrizz** [BSData/wh40k-heralds-of-ruin-killteam#30]
Don't Vanguard Vets get a 10 point discount on power weapons ?
Don't Centurions cost 55 points per model?

**Comment by azdiscord** [comment]
Space Marines kill team list at http://heralds-of-ruin.blogspot.ru/p/kill-team-rules.html states that Vanguard Vets just have access to Melee Weapons, so no discount, and Centurions are 60 pts.  Though it has not been updated to 7E, I think that we should stick to the list until it is updated.

**Comment by dogrizz** [comment]
Well on HoR facebook group exists updated version.
And as far as I know original creator of HoR retired.
So there will be no updates on the site.

**Comment by azdiscord** [comment]
Well, the latest update on HoR site is Adeptus Mechanicus, which been added 07/06/15, and it doesn't looks like they are retired. But maybe you're right, I found updated version on facebook and I will make update ASAP. I think we just need to find a contact with someone from HoR, so the updated lists could be uploaded to their site.
