### ISSUE TITLE
Astra Militarum list issues 

### ISSUE THREAD

**Issue by dchn11** [BSData/wh40k-heralds-of-ruin-killteam#33]
1. Veteran Sergeant is triggering max limit while 2 Guardsmen squads exist in list. Quote from KT List AM: "RESTRICTION: You may only take one Sergeant for every two Guardsmen or Veteran Squad you take." This means that Vet Sarge is taken per 2 x Vets OR Guards.
2. Guardsmen squads can't take special weapons. Quote: "OPTIONS:
• One model in the Squad may replace his lasgun with
one item from the Special Weapons list."
3. It is possible to take 2 special weapons in one Vet Squad. Quote: "• One model in the Squad may replace his lasgun with
one item from the Special Weapons list."

**Comment by azdiscord** [comment]
1 and 2 - unable to reproduce. 3 - will fix soon.
