### ISSUE TITLE
[Anon] Bug report: HoRKT-Eldar.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-heralds-of-ruin-killteam#34]
**File:** HoRKT-Eldar.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Eldar craftworlds fomation - Seer Counseel haven't option to get  a jetbikes.

**Comment by azdiscord** [comment]
What? Eldar craftworlds fomation? Seer Counseel? In Kill Team?
