### ISSUE TITLE
Lack of Dark Eldar

### ISSUE THREAD

**Issue by Dragonoid1976** [BSData/wh40k-heralds-of-ruin-killteam#39]
Running this with Battlescribe 1.15.07 and I noticed that there doesn't seem to be a Dark Eldar catalog. Am I just not seeing it or is there really not one yet, and if it's the latter can you please add one? Thanks in advance. (Note,  new to GitHub,  not sure how to add labels.  Sorry for the inconvenience)

**Comment by aasthen** [comment]
I am very close to finishing the Dark Eldar catalog but I am not sure of the steps to follow to have it online. Can somebody help me out ? Thank you

**Comment by dabrown** [comment]
@aasthen Once it's pull request is merged it will be included in the appspot build for Killteam.

Do you need help with github pull requests?
