### ISSUE TITLE
Centurion Sergeant base cost should be 70pts

### ISSUE THREAD

**Issue by mpepper54** [BSData/wh40k-heralds-of-ruin-killteam#40]
Centurion Sergeant base cost should be 70pts. Currently 65pts.
Check source = https://app.box.com/s/sibmnbadcbtfvz3tx0nt

**Comment by DreadPirateLynx** [comment]
The up-to-date correct base cost is 45pts.

**Comment by DreadPirateLynx** [comment]
Issue solved and can be closed
