### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by williamwm** [BSData/wh40k-heralds-of-ruin-killteam#42]
Hi,

I would like to add and work on the the Adeptus Arbites Kill Team List.

Cheers,

William

**Comment by amis92** [comment]
Hello, I'll invite you to our Games Workshop data authors team - you'll receive an invitation by email. Please accept it either from the email or on the org page: https://github.com/BSData

Please take a (good) look at [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide), and if you have any questions, you can mention (notify) me by writing `@amis92` in your comment.
