### ISSUE TITLE
[Anon] Bug report: HoRKT-Necron.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-heralds-of-ruin-killteam#44]
**File:** HoRKT-Necron.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** In the Team Leader saction, the Nebuloscope is 2 points instead of 10 and the Shadowlomm is 1 point instead of 5. (The cheaper version is only for the Tomb Blade)
Thanks, hope I could help a bit. Love the app!

**Comment by DreadPirateLynx** [comment]
Issue solved and can be closed
