### ISSUE TITLE
Complete Space Wolves Catalogue

### ISSUE THREAD

**Issue by Skjolnir** [BSData/wh40k-heralds-of-ruin-killteam#47]
Hey there,

I started with the Space Wolves Catalogue, but I am currently really busy. That's why I won't finish it before the end of the year.

For those who might be interested in completing it:
I created a branch for the Space Wolves, where all Profiles, Rules and Weapons are already set up.

To-Do:
Create the Unit Profiles and Entry Groups for Weapons and co.

**Comment by bobbit17** [comment]
Not sure if I can do anything to help but I will if I can. Only have a phone. No desktop
