### ISSUE TITLE
[Anon] Bug report: HoRKT-Adepta_Sororitas.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-heralds-of-ruin-killteam#5]
**File:** HoRKT-Adepta_Sororitas.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** The bolt pistol profile is not displayed for the Seraphim.

**Comment by new-neon** [comment]
Old vrersion Adepta Sororitas not supported.
