### ISSUE TITLE
[Anon] Bug report: HoRKT-Adeptus_Arbites.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-heralds-of-ruin-killteam#50]
**File:** HoRKT-Adeptus_Arbites.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** There are not rotas or lists in the adeptus arbiters HoRKT option are they available or is my version corrupted?

**Comment by williamwm** [comment]
The Adeptus Arbites list is not complete yet, we are working on it.

**Comment by DreadPirateLynx** [comment]
Solved and can be closed
