### ISSUE TITLE
[Anon] Bug report: HoRKT-Tau.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-heralds-of-ruin-killteam#53]
**File:** HoRKT-Tau.catz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** Pathfinder Shas'ui for the team leader position is lacking the ability to select the pathfinder 'special' drones (the grav-inhibitor drone, the pulse accelerator drone, and the recon drone), can select only the standard gun/marker/shield drones.

**Comment by DreadPirateLynx** [comment]
Issue solved and can be closed
