### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by beckian** [BSData/wh40k-heralds-of-ruin-killteam#61]
Hello,
I have been using battlescribe for a while now and recently came across Heralds of Ruin. I noticed the tyranids catalog doesn't match up with the current team list and have started to adapt it to make it up to date. I am happy to share this if others get use out of it. I am new to github though so don't really know how this bit works (obviously I will try to get round to reading up on it soon). 

Hope I can help out.

**Comment by amis92** [comment]
Hello, @beckian. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also join our team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!
