### ISSUE TITLE
[Anon] Bug report: HoRKT-Blood_Angels.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-heralds-of-ruin-killteam#67]
**File:** HoRKT-Blood_Angels.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Point Cost for certain units is incorrect as well as options.
Eg: Assault Squad = 85pts and can forego jump-packs to take a free drop-pod or rhino.
Your data file however lists AS at 70pts, jp's at 15 (total = 85 however they come with jp's already), Drop-pod at 35 and rhino at 45 (increased above the allocated cost) They should be placed at 15pts each or a change must be made to replace jp's with either at no additional cost.
I love BS and these data files and use them often - feel bad I only realised now about the cost mistakes...

**Comment by DreadPirateLynx** [comment]
Are you sure you're using the correct game system? Heralds of Ruin Kill Team is an unofficial supplement, not the official GW one. Models are purchased as individuals, not squads, and Transports are purchased separately. What you describe above is the correct cost for all of those units in HoRTK
