### ISSUE TITLE
Vespid Strain Leader Question

### ISSUE THREAD

**Issue by bitfury** [BSData/wh40k-heralds-of-ruin-killteam#8]
Hey guys, I'm currently coding the Tau codex.... Vespid Strain Leader has a special rule that makes Vespid Stingwings (Normally Special) into Core models... Any idea how I can impliment this?

**Comment by new-neon** [comment]
You can make second unit of Vespid Stingwings in core with modifre of max count if Vespid Strain Leader selected in roster

**Comment by bitfury** [comment]
Got it.  THanks!
