### ISSUE TITLE
Appspot battlescribe data

### ISSUE THREAD

**Issue by beckian** [BSData/wh40k-heralds-of-ruin-killteam#91]
The heralds of ruin killteam repo on the http://battlescribedata.appspot.com/#/repos site is dated back in April still.
Are we ready for a new release?

**Comment by DreadPirateLynx** [comment]
A lot of work still needs to be done, but a new release would probably be a good idea, if for no reason than to try to find any bugs left over from the transition to 2.0

**Comment by DreadPirateLynx** [comment]
Pushed release v2.0.0
