### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by ViscousVortex** [BSData/wh40k-heralds-of-ruin-killteam#99]
Hello,

I would like to help develop the data and catalogues for this game. I'm an avid user of battlescribe, and would like to help give back to the community by helping to maintain the data as well.
In the mean time, I'll be reading/watching the introduction material.

**Comment by amis92** [comment]
Hello, @ViscousVortex . Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also join our team in Gitter chat room (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!
